---
- hosts: rke_cluster
  become: yes
  vars:
    addr:
      - 149.165.169.203
  tasks:
    - name: Install nginx
      package:
        name: nginx
        state: present
    - name: Copy nginx configuration
      template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
    - name: Restart nginx service
      service:
        name: nginx
        state: restarted
