---
- hosts: localhost
  tasks:
  - name: Remove the subnet
    os_subnet:
      name: ks-testing-2101-subnet-feb17
      state: absent
  - name: Remove the network
    os_network:
      name: ks-testing-2101-network-feb17
      state: absent
