---
# Copy the welcome.html file to the static directory.
- name: Scoping block
  block:
  - name:  Install the welcome html file
    copy:
      src: files/welcome.html
      dest: "{{ galaxy_static_dir }}/{{ item }}"
      mode: 0644
    loop:
      - welcome.html
      - welcome.html.sample
  remote_user: "{{ galaxy_remote_users.privsep | default(__galaxy_remote_user) }}"
  become: "{{ true if galaxy_become_users.privsep is defined else __galaxy_become }}"
  become_user: "{{ galaxy_become_users.privsep | default(__galaxy_become_user) }}"
