---
- src: galaxyproject.galaxy
  version: 0.9.7
- src: galaxyproject.nginx
  version: 0.6.4
- src: galaxyproject.postgresql
  version: 1.0.3
- src: natefoo.postgresql_objects
  version: 1.1
- src: geerlingguy.pip
  version: 2.0.0
- src: uchida.miniconda
  version: 0.3.0
- src: usegalaxy_eu.galaxy_systemd
  version: 0.1.4
- src: usegalaxy_eu.certbot
  version: 0.1.5
- src: galaxyproject.repos
  version: 0.0.2
- src: galaxyproject.slurm
  version: 0.1.3
- name: usegalaxy_eu.rabbitmq
  version: 0.1.0
- src: galaxyproject.pulsar
  version: 1.0.6
- src: galaxyproject.cvmfs
  version: 0.2.13