---
- name: Testing variables with SUDO=NO
  hosts: galaxyservers
  become: no

  tasks:
    - name: "PLAYBOOK SUDO=NO, TASK SUDO=NO"
      command: whoami
      register: whoami_output
      become: no
    - debug: var=whoami_output.stdout
    - debug: var=ansible_ssh_user
      become: no
    - debug: var=ansible_user_id
      become: no

    - name: "PLAYBOOK SUDO=NO, TASK SUDO=YES"
      command: whoami
      register: whoami_output
      become: yes
    - debug: var=whoami_output.stdout
    - debug: var=ansible_ssh_user
      become: yes
    - debug: var=ansible_user_id
      become: yes

- name: Testing variables with SUDO=YES
  hosts: galaxyservers
  become: yes

  tasks:
    - name: "PLAYBOOK SUDO=YES, TASK SUDO=NO"
      command: whoami
      register: whoami_output
      become: no
    - debug: var=whoami_output.stdout
    - debug: var=ansible_ssh_user
      become: no
    - debug: var=ansible_user_id
      become: no

    - name: "PLAYBOOK SUDO=YES, TASK SUDO=YES"
      command: whoami
      register: whoami_output
      become: yes
    - debug: var=whoami_output.stdout
    - debug: var=ansible_ssh_user
      become: yes
    - debug: var=ansible_user_id
      become: yes


# OUTPUT (condensed):

# PLAY [Testing variables with SUDO=NO] ***************************************** 

# TASK: [PLAYBOOK SUDO=NO, TASK SUDO=NO] **************************************** 
# "whoami_output.stdout": "vagrant"
# "ansible_ssh_user": "vagrant"
# "ansible_user_id": "vagrant"
# 
# TASK: [PLAYBOOK SUDO=NO, TASK SUDO=YES] *************************************** 
# "whoami_output.stdout": "root"
# "ansible_ssh_user": "vagrant"
# "ansible_user_id": "vagrant"


# PLAY [Testing variables with SUDO=YES] **************************************** 

# GATHERING FACTS *************************************************************** 
# TASK: [PLAYBOOK SUDO=YES, TASK SUDO=NO] *************************************** 
# "whoami_output.stdout": "vagrant"
# "ansible_ssh_user": "vagrant"
# "ansible_user_id": "root"
# 
# TASK: [PLAYBOOK SUDO=YES, TASK SUDO=YES] ************************************** 
# "whoami_output.stdout": "root"
# "ansible_ssh_user": "vagrant"
# "ansible_user_id": "root"