---
- hosts: localhost
  vars:
    config: defaults
  vars_files:
    - vars/{{ config }}.yml
  tasks:
    - name: Print the config name we are using
      debug:
        msg: "Config: {{ config }}"
    - name: Print a value from the config.
      debug:
        msg: "Releaese value: {{ release }}"

